# Generated by Django 5.2.8 on 2025-11-19 01:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'otp_verifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('data_consent', models.BooleanField(default=False)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=100)),
                ('age', models.CharField(choices=[('18-25 years old', '18-25 years old'), ('26-35 years old', '26-35 years old'), ('36-45 years old', '36-45 years old'), ('45-55 years old', '45-55 years old'), ('56 above years old', '56 above years old')], max_length=50)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Prefer not to say', 'Prefer not to say')], max_length=50)),
                ('birthdate', models.DateField()),
                ('indigenous_affiliation', models.CharField(blank=True, max_length=200)),
                ('mobile_number', models.CharField(max_length=20)),
                ('facebook_link', models.URLField(max_length=500)),
                ('hobbies', models.TextField()),
                ('organizations', models.TextField()),
                ('street_barangay', models.CharField(max_length=255)),
                ('city_municipality', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=200)),
                ('same_as_permanent', models.BooleanField(default=False)),
                ('up_street_barangay', models.CharField(blank=True, max_length=255)),
                ('up_city_municipality', models.CharField(blank=True, max_length=100)),
                ('up_province', models.CharField(blank=True, max_length=100)),
                ('up_region', models.CharField(blank=True, max_length=200)),
                ('affiliation', models.CharField(choices=[('STUDENT', 'Student'), ('ALUMNI', 'Alumni'), ('UP STAFF', 'UP Staff'), ('FACULTY', 'Faculty'), ('RETIREE', 'Retiree')], max_length=20)),
                ('degree_program', models.CharField(blank=True, max_length=200)),
                ('year_level', models.CharField(blank=True, max_length=50)),
                ('college', models.CharField(blank=True, max_length=50)),
                ('shs_type', models.CharField(blank=True, max_length=200)),
                ('grad_bachelors', models.CharField(blank=True, max_length=255)),
                ('first_college', models.CharField(blank=True, max_length=10)),
                ('first_grad', models.CharField(blank=True, max_length=10)),
                ('first_up', models.CharField(blank=True, max_length=10)),
                ('emer_name', models.CharField(blank=True, max_length=200)),
                ('emer_relation', models.CharField(blank=True, max_length=100)),
                ('emer_contact', models.CharField(blank=True, max_length=20)),
                ('emer_address', models.TextField(blank=True)),
                ('faculty_dept', models.CharField(blank=True, max_length=255)),
                ('constituent_unit', models.CharField(blank=True, max_length=100)),
                ('alumni_degree', models.CharField(blank=True, max_length=200)),
                ('year_grad', models.CharField(blank=True, max_length=4)),
                ('first_grad_college', models.CharField(blank=True, max_length=10)),
                ('first_grad_up', models.CharField(blank=True, max_length=10)),
                ('occupation', models.CharField(blank=True, max_length=255)),
                ('retire_designation', models.CharField(blank=True, max_length=255)),
                ('retire_office', models.CharField(blank=True, max_length=255)),
                ('staff_office', models.CharField(blank=True, max_length=255)),
                ('staff_position', models.CharField(blank=True, max_length=255)),
                ('volunteer_programs', models.JSONField(default=list)),
                ('affirmative_action_subjects', models.JSONField(default=list)),
                ('volunteer_status', models.CharField(choices=[('First time to apply as volunteer (no engagements yet)', 'First time'), ('Already signed up in the previous sign up form but no engagements yet', 'Signed up - no engagements'), ('Signed up in the previous sign up form and already have engagements with Pahinungod', 'Signed up - with engagements')], max_length=255)),
                ('tagapag_ugnay', models.CharField(max_length=3)),
                ('other_organization', models.CharField(max_length=3)),
                ('organization_name', models.CharField(blank=True, max_length=255)),
                ('how_did_you_hear', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Volunteer',
                'verbose_name_plural': 'Volunteers',
                'db_table': 'volunteers',
                'ordering': ['-created_at'],
            },
        ),
    ]
