# Generated by Django 5.2.8 on 2025-11-29 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_event_is_canceled_event_is_deleted'),
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteeraffiliation',
            name='affiliation',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='volunteeraffiliation',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.volunteer'),
        ),
    ]
