# Generated by Django 5.2.8 on 2025-11-19 22:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otpverification',
            options={},
        ),
        migrations.AlterModelOptions(
            name='volunteer',
            options={},
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='affiliation',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='affirmative_action_subjects',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='age',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='alumni_degree',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='city_municipality',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='college',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='constituent_unit',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='data_consent',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='degree_program',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='emer_address',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='emer_contact',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='emer_name',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='emer_relation',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='facebook_link',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='faculty_dept',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='first_college',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='first_grad',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='first_grad_college',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='first_grad_up',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='first_up',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='grad_bachelors',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='hobbies',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='how_did_you_hear',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='indigenous_affiliation',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='organization_name',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='organizations',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='other_organization',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='province',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='region',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='retire_designation',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='retire_office',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='same_as_permanent',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='shs_type',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='staff_office',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='staff_position',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='street_barangay',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='tagapag_ugnay',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='up_city_municipality',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='up_province',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='up_region',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='up_street_barangay',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='volunteer_programs',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='volunteer_status',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='year_grad',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='year_level',
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='nickname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='sex',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterModelTable(
            name='otpverification',
            table=None,
        ),
        migrations.AlterModelTable(
            name='volunteer',
            table=None,
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('relationship', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('volunteer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contact', to='volunteers.volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('password', models.CharField(max_length=255)),
                ('volunteer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='volunteers.volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=255)),
                ('province', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('volunteer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='volunteers.volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerAffiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliation', models.CharField(max_length=50)),
                ('volunteer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affiliation', to='volunteers.volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(blank=True, max_length=255)),
                ('org_affiliation', models.CharField(blank=True, max_length=255)),
                ('hobbies_interests', models.TextField(blank=True)),
                ('volunteer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='background', to='volunteers.volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=20)),
                ('facebook_link', models.URLField(blank=True, max_length=500)),
                ('volunteer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='volunteers.volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_program', models.CharField(blank=True, max_length=200)),
                ('year_level', models.CharField(blank=True, max_length=50)),
                ('college', models.CharField(blank=True, max_length=50)),
                ('department', models.CharField(blank=True, max_length=50)),
                ('year_graduated', models.CharField(blank=True, max_length=4)),
                ('volunteer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='volunteers.volunteer')),
            ],
        ),
    ]
