# Generated by Django 5.2.8 on 2025-11-19 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0002_alter_otpverification_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='otpverification',
            table='otp_verifications',
        ),
    ]
