# Generated by Django 5.2.8 on 2025-11-25 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0003_alter_otpverification_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteeraccount',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
