# Generated by Django 5.2.8 on 2025-11-20 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0003_alter_otpverification_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteeraccount',
            name='username',
            field=models.CharField(default='default_user', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
