# Generated by Django 5.2.8 on 2025-11-25 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0003_alter_otpverification_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTPVerification',
        ),
    ]
