# Generated by Django 5.2.8 on 2025-11-26 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0004_alter_volunteeraccount_email'),
        ('volunteers', '0004_delete_otpverification'),
    ]

    operations = [
    ]
