# Generated by Django 5.2.8 on 2025-11-27 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0005_merge_20251127_0158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteeraffiliation',
            name='volunteer',
        ),
        migrations.RemoveField(
            model_name='volunteeraddress',
            name='volunteer',
        ),
        migrations.RemoveField(
            model_name='volunteerbackground',
            name='volunteer',
        ),
        migrations.RemoveField(
            model_name='volunteercontact',
            name='volunteer',
        ),
        migrations.RemoveField(
            model_name='volunteereducation',
            name='volunteer',
        ),
        migrations.RemoveField(
            model_name='volunteeraccount',
            name='volunteer',
        ),
        migrations.DeleteModel(
            name='EmergencyContact',
        ),
        migrations.DeleteModel(
            name='VolunteerAffiliation',
        ),
        migrations.DeleteModel(
            name='VolunteerAddress',
        ),
        migrations.DeleteModel(
            name='VolunteerBackground',
        ),
        migrations.DeleteModel(
            name='VolunteerContact',
        ),
        migrations.DeleteModel(
            name='VolunteerEducation',
        ),
        migrations.DeleteModel(
            name='Volunteer',
        ),
        migrations.DeleteModel(
            name='VolunteerAccount',
        ),
    ]
