# Generated by Django 5.2.8 on 2025-12-10 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('volunteer_id', models.AutoField(primary_key=True, serialize=False)),
                ('volunteer_identifier', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('nickname', models.CharField(blank=True, max_length=50, null=True)),
                ('sex', models.CharField(max_length=10)),
                ('birthdate', models.DateField()),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended')], default='Active', max_length=20)),
                ('total_hours', models.IntegerField(default=0)),
                ('affiliation_type', models.CharField(blank=True, choices=[('student', 'Student'), ('alumni', 'Alumni'), ('staff', 'UP Staff'), ('faculty', 'Faculty'), ('retiree', 'Retiree')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('max_slots', models.IntegerField(default=10)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.event')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_program', models.CharField(max_length=100)),
                ('year_level', models.CharField(max_length=20)),
                ('college', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('volunteer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to='core.volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_department', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('volunteer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to='core.volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='RetireeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation_while_in_up', models.CharField(max_length=100)),
                ('office_college_department', models.CharField(max_length=255)),
                ('volunteer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retiree_profile', to='core.volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramInterest',
            fields=[
                ('program_interest_id', models.AutoField(primary_key=True, serialize=False)),
                ('program_name', models.CharField(max_length=255)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_interests', to='core.volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='FacultyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('volunteer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_profile', to='core.volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('relationship', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='core.volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='AlumniProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constituent_unit', models.CharField(max_length=100)),
                ('degree_program', models.CharField(max_length=100)),
                ('year_graduated', models.CharField(max_length=4)),
                ('volunteer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alumni_profile', to='core.volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerAccount',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='core.volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerAddress',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('street_address', models.CharField(max_length=255)),
                ('province', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='core.volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerBackground',
            fields=[
                ('background_id', models.AutoField(primary_key=True, serialize=False)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('org_affiliation', models.CharField(blank=True, max_length=255, null=True)),
                ('hobbies_interests', models.TextField(blank=True, null=True)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backgrounds', to='core.volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerContact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('mobile_number', models.CharField(max_length=15)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='core.volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_rendered', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Joined', 'Joined'), ('Completed', 'Completed'), ('Dropped', 'Dropped')], default='Joined', max_length=20)),
                ('availability_time', models.CharField(blank=True, max_length=255, null=True)),
                ('availability_orientation', models.BooleanField(default=False)),
                ('signup_date', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.event')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.volunteer')),
            ],
            options={
                'unique_together': {('volunteer', 'event')},
            },
        ),
        migrations.CreateModel(
            name='VolunteerScheduleSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteers', to='core.eventschedule')),
                ('volunteer_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_selections', to='core.volunteerevent')),
            ],
            options={
                'unique_together': {('volunteer_event', 'schedule')},
            },
        ),
    ]
