# Generated by Django 5.2.8 on 2025-12-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerscheduleselection',
            name='hours_rendered',
            field=models.FloatField(default=0),
        ),
    ]
