# Generated by Django 5.2.8 on 2025-12-11 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_volunteerscheduleselection_hours_rendered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programinterest',
            name='program_interest_id',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='volunteerbackground',
            name='occupation',
        ),
        migrations.AddField(
            model_name='programinterest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='contact_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='programinterest',
            name='program_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='volunteeraddress',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='volunteeraddress',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='volunteeraddress',
            name='street_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='volunteercontact',
            name='mobile_number',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='VolunteerMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volunteer_status', models.CharField(blank=True, max_length=255, null=True)),
                ('tagapag_ugnay', models.CharField(blank=True, max_length=10, null=True)),
                ('other_organization', models.CharField(blank=True, max_length=10, null=True)),
                ('organization_name', models.CharField(blank=True, max_length=255, null=True)),
                ('affirmative_action_subjects', models.JSONField(default=list)),
                ('how_did_you_hear', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('volunteer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta', to='core.volunteer')),
            ],
        ),
    ]
