# Generated by Django 5.2.8 on 2025-11-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_affiliation_table_alter_emergencycontact_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteeraccount',
            name='username',
            field=models.CharField(default='temp_user', max_length=150, unique=True),
        ),
    ]
