# Generated by Django 5.2.8 on 2025-11-29 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_eventschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='volunteer_identifier',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
