# Generated by Django 5.2.8 on 2025-11-29 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_volunteer_volunteer_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
