# Generated by Django 5.2.8 on 2025-11-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_event_is_canceled_event_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='year_level',
            field=models.CharField(max_length=20),
        ),
    ]
