# Generated by Django 5.2.8 on 2025-12-05 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_studentprofile_year_level'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='volunteerevent',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='volunteerevent',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.eventschedule'),
        ),
        migrations.AlterUniqueTogether(
            name='volunteerevent',
            unique_together={('volunteer', 'event', 'schedule')},
        ),
    ]
